export const skills = {
  jsts: "Javascript / Typescript",
  react: "React",
  python: "Python",
  node: "Node.js",
  gql: "GraphQL",
  pyside6: "Pyside6",
  sql: "SQL",
  nosql: "No-SQL",
  selenium: "Selenium",
  maven: "Maven",
  springBoot: "Spring Boot",
  reactNative: "React Native",
  c: "C++",
};
